apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: node-api-conversao
  template:
    metadata:
      labels:
        app: node-api-conversao
    spec:
      containers:
        - name: site
          image: al3xant/api-conversao:v1
          ports:
            - containerPort: 3000
